image: gcc

stages:
  - build
  - test

variables:
  MAKE: make

build:
  stage: build
  script:
    - ${MAKE} maze

test:
  stage: test
  script:
    - ${MAKE} run
  artifacts:
    files:
      - maze