image: gcc

stages:
  - build
  - test
  - doc
  - clean

variables:
  MAKE: make
  DOXYGEN_IMAGE: "doxygen/doxygen:latest"

build:
  stage: build
  script:
    - ${MAKE} maze
  artifacts:
    paths:
      - obj
      - ./maze
    when: on_success

doc:
  stage: doc
  script:
    - docker run -v $(pwd):/app $DOXYGEN_IMAGE doxygen Doxyfile
    - ${MAKE} pdf
  artifacts:
    paths:
      - doc/latex/refman.pdf
    when: on_success

test:
  stage: test
  script:
    - ${MAKE} run

clean:
  stage: clean
  script:
    - ${MAKE} clean